# Form implementation generated from reading ui file 'tic-tac-toe_ver1.2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(213, 319)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.clicked.connect(self.put_x_0)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.clicked.connect(self.put_x_0)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 80, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.clicked.connect(self.put_x_0)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 150, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_4.clicked.connect(self.put_x_0)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 10, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.clicked.connect(self.put_x_0)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 80, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_6.clicked.connect(self.put_x_0)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 150, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_7.clicked.connect(self.put_x_0)
        self.pushButton_7.setGeometry(QtCore.QRect(140, 10, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_8.clicked.connect(self.put_x_0)
        self.pushButton_8.setGeometry(QtCore.QRect(140, 80, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_9.clicked.connect(self.put_x_0)
        self.pushButton_9.setGeometry(QtCore.QRect(140, 150, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.buttons = [[self.pushButton, self.pushButton_2, self.pushButton_3], [self.pushButton_4, self.pushButton_5,
                        self.pushButton_6], [self.pushButton_7, self.pushButton_8, self.pushButton_9]]
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 260, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"color:green\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_10 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_10.clicked.connect(self.reset)
        self.pushButton_10.setGeometry(QtCore.QRect(50, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"background-color: red\n"
"}")
        self.pushButton_10.setFlat(False)
        self.pushButton_10.setObjectName("pushButton_10")

        self.x = True

        self.counter = 0

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Tic-Tac-Toe"))
        self.pushButton_10.setText(_translate("Form", "Reset"))

    def reset(self):
        for i in self.buttons:
            for j in i:
                j.setText('')
        self.x = True
        self.label.setText('')
        self.unlock_buttons()
        self.counter = 0


    def put_x_0(self):
        btn = self.label.sender()
        if self.x is True:
            btn.setText('X')
        else:
            btn.setText('0')
        self.x = not self.x
        self.counter += 1
        self.check_win()
        if self.counter == 9 and self.check_win() is None:
            self.label.setText('Draw')
            self.block_buttons()


    def check_win(self):
        field1 = [[self.buttons[i][j].text() for i in range(3)] for j in range(3)]
        field2 = [[field1[j][i] for j in range(3)] for i in range(3)]

        for i in range(3):
            if field1[i] == ['X', 'X', 'X'] or field2[i] == ['X', 'X', 'X']:
                self.label.setText('X Wins')
                self.block_buttons()
                return 'X'
            elif field1[i] == ['0', '0', '0'] or field2[i] == ['0', '0', '0']:
                self.label.setText('0 Wins')
                self.block_buttons()
                return 'Y'
        if field1[0][0] == field1[1][1] == field1[2][2] != '' or field1[2][0] == field1[1][1] == field1[0][2] != '':
            self.label.setText(f'{field1[1][1]} Wins')
            return f'{field1[1][1]}'

    def block_buttons(self):
        for i in range(3):
            for j in range(3):
                self.buttons[i][j].setEnabled(False)

    def unlock_buttons(self):
        for i in range(3):
            for j in range(3):
                self.buttons[i][j].setEnabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
